#!/usr/bin/env python3
"""Consolidate HELIOS phased markdown files into a single deterministic document."""
from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUTPUT = ROOT / "docs" / "phases" / "ALL_PHASED_MDS_CONSOLIDATED.md"
SKIP_DIRS = {".git", ".vs", ".vscode", "bin", "obj", "node_modules", "packages", ".pytest_cache", "__pycache__"}
SKIP_NAMES = {OUTPUT.name}


def natural_key(path: Path) -> list[object]:
    text = path.relative_to(ROOT).as_posix().lower()
    return [int(part) if part.isdigit() else part for part in re.split(r"(\d+)", text)]


def is_phase_markdown(path: Path) -> bool:
    if path.suffix.lower() != ".md":
        return False
    relative_parts = path.relative_to(ROOT).parts
    if any(part in SKIP_DIRS for part in relative_parts):
        return False
    if path.name in SKIP_NAMES:
        return False
    lower_name = path.name.lower()
    return "phase" in lower_name or "phases" in relative_parts


def title_for(path: Path) -> str:
    relative = path.relative_to(ROOT).as_posix()
    return relative.replace("_", "\\_")


def read_text(path: Path) -> str:
    text = path.read_text(encoding="utf-8", errors="replace")
    return "\n".join(line.rstrip() for line in text.splitlines()).rstrip()


def main() -> int:
    phase_docs = sorted((path for path in ROOT.rglob("*.md") if is_phase_markdown(path)), key=natural_key)
    lines: list[str] = [
        "# HELIOS Consolidated Phased Markdown Documentation",
        "",
        "Generated by: `python3 scripts/docs/consolidate_phased_docs.py`",
        f"Source files consolidated: `{len(phase_docs)}`",
        "",
        "> This file is intentionally generated from every markdown file whose path or file name is phase-oriented.",
        "> Keep source phase files authoritative for edits, then regenerate this document with `python3 scripts/docs/consolidate_phased_docs.py`.",
        "",
        "## Source index",
        "",
        "| # | Source | Bytes |",
        "| ---: | --- | ---: |",
    ]
    for index, path in enumerate(phase_docs, start=1):
        relative = path.relative_to(ROOT).as_posix()
        lines.append(f"| {index} | `{relative}` | {path.stat().st_size} |")

    lines.extend(["", "## Consolidated source content", ""])
    for index, path in enumerate(phase_docs, start=1):
        relative = path.relative_to(ROOT).as_posix()
        content = read_text(path)
        lines.extend([
            "---",
            "",
            f"## {index}. `{title_for(path)}`",
            "",
            f"Source: `{relative}`",
            "",
        ])
        if content:
            lines.append(content)
            lines.append("")
        else:
            lines.extend(["_Empty source file._", ""])

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    print(f"Wrote {OUTPUT.relative_to(ROOT)} from {len(phase_docs)} source files")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
