const reportSources=['reports/agents/agent-party.json','reports/agents/agent-xp.json','reports/final-gate/final-gate.json','reports/mass-integration/mass-integration-score.json','reports/mass-integration/conflict-forecast.json','reports/policy/policy-gate.json','reports/security/vault-readiness.json','reports/model-store/models.json','reports/github-takeover/status.json','reports/microsoft365/copilot-readiness.json','reports/hermes-xcore/models.json'];
const party=[
  {slot:'Leader',name:'csharp-core',job:'C# Vanguard',xp:60,abilities:['Compile Break','Namespace Mend','Contract Guard'],cmd:'./tools/helios.ps1 fix csharp'},
  {slot:'Guardian',name:'azure-infra',job:'Azure Oracle',xp:70,abilities:['What-If Sight','Vault Seal','Deploy Ward'],cmd:'./tools/helios.ps1 azure report-what-if'},
  {slot:'Scout',name:'mass-integration',job:'Merge Ronin',xp:80,abilities:['Safe Merge','Conflict Sense','Auto-PR'],cmd:'./tools/helios.ps1 github conflict-forecast'},
  {slot:'Sage',name:'hermes-xcore',job:'XCore Sage',xp:55,abilities:['Model Swap','Token Aura','Local Fallback'],cmd:'./tools/helios.ps1 hermes models'}
];
const shops=[['Deep Setup','./tools/helios.ps1 setup deep-all'],['Agent Party','./tools/helios.ps1 agents party'],['Model Store','./tools/helios.ps1 models list'],['GitHub Takeover','./tools/helios.ps1 github takeover'],['Copilot/M365','./tools/helios.ps1 m365 copilot'],['Audit','./tools/helios.ps1 audit latest']];
const app=document.getElementById('app');
function copy(c){navigator.clipboard.writeText(c)}
app.innerHTML=`<section class="hero"><h2>Fleet XP ${party.reduce((a,p)=>a+p.xp,0)}</h2><p>JRPG-style control: party members, abilities, setup shop, model store, GitHub takeover, Hermes/XCore models, Copilot/M365 readiness.</p></section><section class="grid">${party.map(p=>`<div class="card party"><h2>${p.slot}: ${p.name}</h2><h3>${p.job} · Lv ${Math.max(1,Math.floor(p.xp/25))}</h3><div class="bar"><span style="width:${Math.min(100,p.xp)}%"></span></div><p>${p.abilities.map(a=>`<b class="ability">${a}</b>`).join(' ')}</p><button onclick="copy('${p.cmd}')">Copy ability command</button></div>`).join('')}${shops.map(([l,c])=>`<div class="card shop"><h2>${l}</h2><button onclick="copy('${c}')">Copy setup: ${c}</button></div>`).join('')}${reportSources.map(r=>`<div class="card"><h2>${r}</h2><pre>Report source: ${r}</pre></div>`).join('')}</section>`;
