#!/usr/bin/env python3
"""Prepare HELIOS external repository consolidation safely.

This script is intentionally conservative:
- it never merges, subtrees, or writes .gitmodules directly;
- it can perform offline manifest/report generation;
- online reachability checks fail closed unless --allow-unreachable is supplied;
- --apply only adds/fetches remotes after all requested pre-merge gates pass.
"""
from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from dataclasses import asdict, dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
MANIFEST = ROOT / "MERGE_SOURCE_MANIFEST.yaml"
ARTIFACT_DIR = ROOT / "artifacts" / "consolidation"


@dataclass
class Source:
    id: str
    kind: str = ""
    git_remote_name: str = ""
    git_remote_url_or_local_path: str = ""
    source_branch: str = "main"
    target_branch: str = "main"
    submodule_path: str = ""
    consolidation_mode: str = ""
    merge_order: int = 999


def parse_manifest() -> list[Source]:
    """Parse the manifest subset required for consolidation without PyYAML."""
    sources: list[Source] = []
    current: dict[str, object] | None = None
    in_sources = False

    for raw in MANIFEST.read_text(encoding="utf-8").splitlines():
        line = raw.rstrip()
        if line.startswith("merge_sources:"):
            in_sources = True
            continue
        if not in_sources:
            continue

        stripped = line.strip()
        if stripped.startswith("- id:"):
            if current:
                sources.append(Source(**{k: v for k, v in current.items() if k in Source.__dataclass_fields__}))
            current = {"id": stripped.split(":", 1)[1].strip().strip('"\'')}
            continue

        if current is None or not stripped or stripped.startswith("#") or ":" not in stripped:
            continue

        key, value = stripped.split(":", 1)
        key = key.strip()
        if key not in Source.__dataclass_fields__:
            continue

        value = value.strip().strip('"\'')
        if key == "merge_order":
            try:
                current[key] = int(value)
            except ValueError:
                current[key] = 999
        else:
            current[key] = value

    if current:
        sources.append(Source(**{k: v for k, v in current.items() if k in Source.__dataclass_fields__}))

    return sorted(sources, key=lambda source: source.merge_order)


def git(args: list[str], check: bool = False) -> subprocess.CompletedProcess[str]:
    env = os.environ.copy()
    env["GIT_TERMINAL_PROMPT"] = "0"
    return subprocess.run(["git", *args], cwd=ROOT, env=env, text=True, capture_output=True, check=check)


def remote_head(source: Source, *, online: bool) -> tuple[bool, str, str, str]:
    """Return reachable, sha, error, and check mode for a source."""
    if source.kind == "current_repository":
        result = git(["rev-parse", "HEAD"])
        return result.returncode == 0, result.stdout.strip(), result.stderr.strip(), "local"

    if not online:
        return False, "", "skipped: offline mode", "offline"

    if not source.git_remote_url_or_local_path:
        return False, "", "missing remote url/path", "online"

    result = git(["ls-remote", "--heads", source.git_remote_url_or_local_path, source.source_branch])
    if result.returncode != 0:
        return False, "", result.stderr.strip(), "online"

    parts = result.stdout.strip().split()
    if not parts:
        return False, "", f"branch {source.source_branch!r} not found", "online"

    return True, parts[0], "", "online"


def configure_remote(source: Source) -> None:
    if source.kind == "current_repository" or not source.git_remote_name:
        return

    existing = git(["remote", "get-url", source.git_remote_name])
    if existing.returncode == 0:
        if existing.stdout.strip() != source.git_remote_url_or_local_path:
            git(["remote", "set-url", source.git_remote_name, source.git_remote_url_or_local_path], check=True)
    else:
        git(["remote", "add", source.git_remote_name, source.git_remote_url_or_local_path], check=True)

    git(["fetch", "--prune", source.git_remote_name, source.source_branch], check=True)


def write_gitmodules_preview(sources: list[Source]) -> Path:
    lines = [
        "# Preview only. Review and copy to .gitmodules only after every source is reachable.",
        "# Generated by scripts/github/prepare-consolidation.py --write-gitmodules-preview.",
        "",
    ]
    for source in sources:
        if source.kind == "current_repository" or not source.submodule_path:
            continue
        lines.extend(
            [
                f'[submodule "{source.id}"]',
                f"\tpath = {source.submodule_path}",
                f"\turl = {source.git_remote_url_or_local_path}",
                f"\tbranch = {source.source_branch}",
                "",
            ]
        )

    ARTIFACT_DIR.mkdir(parents=True, exist_ok=True)
    preview = ARTIFACT_DIR / "gitmodules.preview"
    preview.write_text("\n".join(lines), encoding="utf-8")
    return preview


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--dry-run", action="store_true", help="validate/report only; do not change git remotes")
    mode.add_argument("--apply", action="store_true", help="add/fetch remotes after reachability gates pass")

    network = parser.add_mutually_exclusive_group()
    network.add_argument("--online", action="store_true", help="perform network reachability checks (default)")
    network.add_argument("--offline", action="store_true", help="skip external network checks and generate manifest-derived reports only")

    parser.add_argument("--allow-unreachable", action="store_true", help="return success after reporting unreachable/private sources")
    parser.add_argument("--fail-on-unreachable", action="store_true", help="return non-zero if any requested source is unreachable")
    parser.add_argument("--write-gitmodules-preview", action="store_true", help="write artifacts/consolidation/gitmodules.preview")
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)

    online = not args.offline
    sources = parse_manifest()
    report = []
    failures = []

    for source in sources:
        reachable, sha, error, check_mode = remote_head(source, online=online)
        item = asdict(source)
        item.update({"reachable": reachable, "head_sha": sha, "error": error, "check_mode": check_mode})
        report.append(item)

        status = "OK" if reachable else ("SKIP" if check_mode == "offline" else "FAIL")
        detail = sha or error
        print(f"[{status}] {source.id} {source.git_remote_url_or_local_path or '(current)'} {source.source_branch} {detail}")
        if not reachable and check_mode != "offline":
            failures.append(source.id)

    ARTIFACT_DIR.mkdir(parents=True, exist_ok=True)
    report_path = ARTIFACT_DIR / "consolidation-report.json"
    report_path.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote {report_path.relative_to(ROOT)}")

    if args.write_gitmodules_preview:
        preview = write_gitmodules_preview(sources)
        print(f"Wrote {preview.relative_to(ROOT)}")

    if failures:
        print("Consolidation pre-merge gate failed for: " + ", ".join(failures))
        if args.allow_unreachable and not args.fail_on_unreachable:
            print("Continuing because --allow-unreachable was supplied.")
        else:
            return 2

    if args.apply:
        if args.offline:
            parser.error("--apply requires online mode")
        for source in sources:
            configure_remote(source)
        print("Configured and fetched all reachable external remotes.")
    else:
        print("Report complete; no remotes, submodules, subtree merges, or branch merges were modified.")

    return 0


if __name__ == "__main__":
    sys.exit(main())
